// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Destination - Represents a holiday destination.
type Destination struct {
	// The country where the destination is located.
	Country string `json:"country"`
	// A brief description of the destination.
	Description string `json:"description"`
	// The name of the holiday destination.
	Name string `json:"name"`
	// Rating of the destination (0 to 5).
	Rating float64 `json:"rating"`
}

func (o *Destination) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *Destination) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Destination) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Destination) GetRating() float64 {
	if o == nil {
		return 0.0
	}
	return o.Rating
}
