// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"context"
	"mockserver/internal/logging"
	"mockserver/internal/tracking"
	"net/http"
)

// GeneratedHandlers returns all generated handlers.
func GeneratedHandlers(ctx context.Context, dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) []*GeneratedHandler {
	return []*GeneratedHandler{
		NewGeneratedHandler(ctx, http.MethodDelete, "/destinations/{destination_id}", pathDeleteDestinationsDestinationID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/", pathGet(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/destinations", pathGetDestinations(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodGet, "/destinations/{destination_id}", pathGetDestinationsDestinationID(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPost, "/destinations", pathPostDestinations(dir, rt)),
		NewGeneratedHandler(ctx, http.MethodPut, "/destinations/{destination_id}", pathPutDestinationsDestinationID(dir, rt)),
	}
}
