// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteDestinationDestinationsDestinationIDDeleteRequest struct {
	// The ID of the destination to delete.
	DestinationID int64 `pathParam:"style=simple,explode=false,name=destination_id"`
}

func (o *DeleteDestinationDestinationsDestinationIDDeleteRequest) GetDestinationID() int64 {
	if o == nil {
		return 0
	}
	return o.DestinationID
}

type DeleteDestinationDestinationsDestinationIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteDestinationDestinationsDestinationIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
