// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetDestinationByIDDestinationsDestinationIDGetRequest struct {
	// The ID of the destination to retrieve.
	DestinationID int64 `pathParam:"style=simple,explode=false,name=destination_id"`
}

func (o *GetDestinationByIDDestinationsDestinationIDGetRequest) GetDestinationID() int64 {
	if o == nil {
		return 0
	}
	return o.DestinationID
}

type GetDestinationByIDDestinationsDestinationIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Destination *components.Destination
}

func (o *GetDestinationByIDDestinationsDestinationIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDestinationByIDDestinationsDestinationIDGetResponse) GetDestination() *components.Destination {
	if o == nil {
		return nil
	}
	return o.Destination
}
