// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateDestinationDestinationsDestinationIDPutRequest struct {
	// The ID of the destination to update.
	DestinationID int64                  `pathParam:"style=simple,explode=false,name=destination_id"`
	Destination   components.Destination `request:"mediaType=application/json"`
}

func (o *UpdateDestinationDestinationsDestinationIDPutRequest) GetDestinationID() int64 {
	if o == nil {
		return 0
	}
	return o.DestinationID
}

func (o *UpdateDestinationDestinationsDestinationIDPutRequest) GetDestination() components.Destination {
	if o == nil {
		return components.Destination{}
	}
	return o.Destination
}

type UpdateDestinationDestinationsDestinationIDPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Destination *components.Destination
}

func (o *UpdateDestinationDestinationsDestinationIDPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateDestinationDestinationsDestinationIDPutResponse) GetDestination() *components.Destination {
	if o == nil {
		return nil
	}
	return o.Destination
}
