"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from holiday_destinations.types import BaseModel
from typing_extensions import TypedDict


class DestinationTypedDict(TypedDict):
    r"""Represents a holiday destination."""

    country: str
    r"""The country where the destination is located."""
    description: str
    r"""A brief description of the destination."""
    name: str
    r"""The name of the holiday destination."""
    rating: float
    r"""Rating of the destination (0 to 5)."""


class Destination(BaseModel):
    r"""Represents a holiday destination."""

    country: str
    r"""The country where the destination is located."""

    description: str
    r"""A brief description of the destination."""

    name: str
    r"""The name of the holiday destination."""

    rating: float
    r"""Rating of the destination (0 to 5)."""
