"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from holiday_destinations.types import BaseModel
from holiday_destinations.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetDestinationByIDDestinationsDestinationIDGetRequestTypedDict(TypedDict):
    destination_id: int
    r"""The ID of the destination to retrieve."""


class GetDestinationByIDDestinationsDestinationIDGetRequest(BaseModel):
    destination_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the destination to retrieve."""
