"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from holiday_destinations.types import BaseModel
from holiday_destinations.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetDestinationsDestinationsGetRequestTypedDict(TypedDict):
    min_rating: NotRequired[float]
    r"""Filter destinations by minimum rating (0 to 5)."""


class GetDestinationsDestinationsGetRequest(BaseModel):
    min_rating: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Filter destinations by minimum rating (0 to 5)."""
