"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .destination import Destination, DestinationTypedDict
from holiday_destinations.types import BaseModel
from holiday_destinations.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateDestinationDestinationsDestinationIDPutRequestTypedDict(TypedDict):
    destination_id: int
    r"""The ID of the destination to update."""
    destination: DestinationTypedDict


class UpdateDestinationDestinationsDestinationIDPutRequest(BaseModel):
    destination_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the destination to update."""

    destination: Annotated[
        Destination,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
