"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from holiday_destinations import HolidayDestinations
import os
from tests.test_client import create_test_http_client


def test_general_read_root_get():
    with HolidayDestinations(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("read_root__get"),
    ) as holiday_destinations:
        assert holiday_destinations is not None

        res = holiday_destinations.general.read_root_get()
        assert res is not None
        assert res is not None
        assert res == "<value>"
