"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import holiday_destinations
from holiday_destinations import HolidayDestinations
import os
from tests.test_client import create_test_http_client


def test_destinations_get_destinations_destinations_get():
    with HolidayDestinations(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("get_destinations_destinations_get"),
    ) as holiday_destinations:
        assert holiday_destinations is not None

        res = holiday_destinations.destinations.get_destinations_destinations_get()
        assert res is not None
        assert res is not None
        assert res == [
            holiday_destinations.Destination(
                country="Indonesia",
                description="Beautiful beaches and vibrant culture.",
                name="Bali",
                rating=4.8,
            ),
            holiday_destinations.Destination(
                country="Indonesia",
                description="Beautiful beaches and vibrant culture.",
                name="Bali",
                rating=4.8,
            ),
        ]


def test_destinations_create_destination_destinations_post():
    with HolidayDestinations(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("create_destination_destinations_post"),
    ) as holiday_destinations:
        assert holiday_destinations is not None

        res = holiday_destinations.destinations.create_destination_destinations_post(
            country="Indonesia",
            description="Beautiful beaches and vibrant culture.",
            name="Bali",
            rating=4.8,
        )
        assert res is not None
        assert res is not None
        assert res == holiday_destinations.Destination(
            country="Indonesia",
            description="Beautiful beaches and vibrant culture.",
            name="Bali",
            rating=4.8,
        )


def test_destinations_delete_destination_destinations_destination_id_delete():
    with HolidayDestinations(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client(
            "delete_destination_destinations__destination_id__delete"
        ),
    ) as holiday_destinations:
        assert holiday_destinations is not None

        holiday_destinations.destinations.delete_destination_destinations_destination_id_delete(
            destination_id=0
        )


def test_destinations_get_destination_by_id_destinations_destination_id_get():
    with HolidayDestinations(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client(
            "get_destination_by_id_destinations__destination_id__get"
        ),
    ) as holiday_destinations:
        assert holiday_destinations is not None

        res = holiday_destinations.destinations.get_destination_by_id_destinations_destination_id_get(
            destination_id=0
        )
        assert res is not None
        assert res is not None
        assert res == holiday_destinations.Destination(
            country="Indonesia",
            description="Beautiful beaches and vibrant culture.",
            name="Bali",
            rating=4.8,
        )


def test_destinations_update_destination_destinations_destination_id_put():
    with HolidayDestinations(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client(
            "update_destination_destinations__destination_id__put"
        ),
    ) as holiday_destinations:
        assert holiday_destinations is not None

        res = holiday_destinations.destinations.update_destination_destinations_destination_id_put(
            destination_id=1,
            country="Indonesia",
            description="Beautiful beaches and vibrant culture.",
            name="Bali",
            rating=4.8,
        )
        assert res is not None
        assert res is not None
        assert res == holiday_destinations.Destination(
            country="Indonesia",
            description="Beautiful beaches and vibrant culture.",
            name="Bali",
            rating=4.8,
        )
